### ISSUE TITLE
ungrep unrelated data 

### ISSUE THREAD

**Issue by nenadzaric** [trickest/cve#13]
We should create blacklists for github repositories that are known not to be reliable sources.

**Comment by nenadzaric** [comment]
This can be done by removing all files by ```egrep -w --with-filename -w -f refs.txt *``` where ```refs.txt``` is a file with a pattern that is known to be unrelated or used for marketing purposes inside of ```github-pocs``` node.

**Comment by mhmdiaa** [comment]
Resolved in the latest workflow
